### ISSUE TITLE
Passing variables values to the template_media_player's underlying service

### ISSUE THREAD

**Issue by homemain** [EuleMitKeule/template-media-player#2]
Hi! 

First of all - thanks a lot for your efforts in maintaining this repo! It helps me a lot.

I have a very custom device to play music. I have a Python script that can initiate playing, having the filename as an input. Now I'm trying to build a "wrapper" around this Python script using `template_media_player` and `pyscript`. My problem is that I can not pass `media_content_id `from the very top of this call stack to the Python script itself. Can you help me with it?

Layer 2. I have `pyscript` that can play music on a custom device.
```python
@service
def play_media_wyze(media_content_id, media_content_type):
    # play_on_a_special_device(media_content_id)
    system_log.write(message=media_content_id)
```

Layer 1. I have an instance of the `media_player_template`, that overrides `play_media` method by calling my `pyscript`
```yaml
  - platform: media_player_template
    media_players:
      my_media_player:
        friendly_name: media_player_wyze
        play_media:
          service: pyscript.play_media_wyze
          data:
            media_content_id: "{{ media_content_id }}"
            media_content_type: "{{ media_content_type }}"
```

Layer 0. On the top level, I have `media_player.play_media` service call with some input params
```yaml
service: media_player.play_media
data:
  media_content_id: "TEST.wav"
  media_content_type: "music"
Target:
  entity_id: media_player.my_media_player
```

My problem is that I don't know how to describe in YAML on Layer 1 passing `media_content_id` from the top level down to the `pyscript`. Tried several options, including `"media_content_id: "{{ media_content_id }}"` - nothing works. 

Thanks in advance for your assistance.

**Comment by EuleMitKeule** [comment]
Hey, thanks for the feedback. Glad this project is of help!

It should work when you use `{{ media_type }}` and `{{ media_id }}` for the variables:

```yaml
  - platform: media_player_template
    media_players:
      my_media_player:
        friendly_name: media_player_wyze
        play_media:
          service: pyscript.play_media_wyze
          data:
            media_content_id: "{{ media_id }}"
            media_content_type: "{{ media_type }}"
```

The reason for the name discrepancy is that I chose to name the template variables after the argument names of the `async_play_media` (and other) function. I don't know why Home Assistant uses different names for the service parameters and argument names, but I think it's more coherent this way.

I'll add this information to the Readme.
