### ISSUE TITLE
Add support for `media_source`

### ISSUE THREAD

**Issue by pspot2** [EuleMitKeule/template-media-player#3]
Hi Lennard,

first of all, many thanks for your awesome work. This seems to be a missing piece of the puzzle in order to be able to build own custom media players.

While I was able to get this working directly, media players in general can be called by other config entities, for example `tts.speak`. When this happens, the value that the parent entity puts into the `media_id` variable is a `media_source://` URL. Custom media players (especially when using local binaries to play media) of course do not know how to resolve this URI scheme as it is specific to HA. Now, there was an announcement quite some time ago that TTS services would need to support `media_source` (which they do now) - [click](https://developers.home-assistant.io/blog/2022/04/26/tts-say-media-source/). There are also some instructions on what to add to media player methods in order to resolve that URI scheme: [click](https://developers.home-assistant.io/blog/2022/04/26/tts-say-media-source/).

I did some very dirty copy-paste adjustment just to quickly test:

```
--- media_player_orig.py        2024-05-04 00:31:58.005933748 +0200
+++ media_player.py     2024-05-04 00:29:32.029323682 +0200
@@ -5,6 +5,10 @@
 
 import homeassistant.helpers.config_validation as cv
 import voluptuous as vol
+from homeassistant.components import media_source
+from homeassistant.components.media_player.browse_media import (
+    async_process_play_media_url,
+)
 from homeassistant.components.media_player import DOMAIN as DOMAIN_MEDIA_PLAYER
 from homeassistant.components.media_player import (
     ENTITY_ID_FORMAT,
@@ -606,6 +610,13 @@
         self, media_type: MediaType | str, media_id: str, **kwargs
     ):
         if CONF_PLAY_MEDIA_SCRIPT in self._service_scripts:
+            if media_source.is_media_source_id(media_id):
+                media_type = MediaType.MUSIC
+                play_item = await media_source.async_resolve_media(self.hass, media_id, self.entity_id)
+                # play_item returns a relative URL if it has to be resolved on the Home Assistant host
+                # This call will turn it into a full URL
+                media_id = async_process_play_media_url(self.hass, play_item.url)
+
             await self._service_scripts[CONF_PLAY_MEDIA_SCRIPT].async_run(
                 {"media_type": media_type, "media_id": media_id}, context=self._context
             )
```

...and this worked without a snag. The media player resolved the `media_source` URI to a TTS file URI and my custom media player binary was able to play that media file. I'd therefore kindly ask you to adjust your implementation accordingly.

Here is my config (just FYI):

```
shell_command:
    play_sound_file: "/my/custom/binary {{ media_content_id }}"

media_player:
  - platform: template_media_player
    media_players:
        my_media_player:
            unique_id: my_media_player
            friendly_name: My Media Player
            device_class: speaker
            state_template: "on"
            service_scripts:
                play_media:
                  - service: shell_command.play_sound_file
                    data_template:
                        media_content_id: "{{ media_id }}"
                        media_content_type: "{{ media_type }}"

service: tts.speak
target:
    entity_id: tts.piper
data:
    cache: true
    media_player_entity_id: media_player.my_media_player
    message: This is a test message
```
