### ISSUE TITLE
Template entity_id in service_scripts

### ISSUE THREAD

**Issue by balk77** [EuleMitKeule/template-media-player#4]
Hi, thanks for this nice custom component. I would like to use a template in the service scripts section. I have

```
global_template: >
        {% set player = states('input_select.moode_mediaplayers') %}
```
and it picks up the attributes correctly. But when I try this, it does not work:
```
service_scripts:
        media_next_track:
            service: media_player.media_next_track
            data_template:
              entity_id: "{{ player }}"
```
Is it possible to template the player as such?

**Comment by EuleMitKeule** [comment]
Fixed on master: `service_scripts` now receive the entity `variables`, so templated `entity_id` values work.

`global_template` `{% set player = ... %}` is still only prepended to entity templates, not scripts. For a dynamic player in scripts use:

```yaml
variables:
  player: "{{ states('input_select.moode_mediaplayers') }}"
service_scripts:
  media_next_track:
    - action: media_player.media_next_track
      target:
        entity_id: "{{ player }}"
```
